runtime: php

env: flex

runtime_config:
  document_root: .

handlers:
- url: /(.+\.(html|png|jpg|js|css))$
  static_files: \1
  upload: .+\.(html|png|jpg|js|css)$

- url: /.*
  script: auto

entrypoint:
  serve handler.php

env_variables:
  CLOUDSQL_USER: root
  CLOUDSQL_DB: COSGymPatronData
  CLOUDSQL_PASSWORD: Ilneu070393@2
  CLOUDSQL_DSN: /cloudsql/cosgym:us-central1:cosgympatrondata